// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mrwin_fast_pair_cpp
NumericVector mrwin_fast_pair_cpp(NumericMatrix time_high, IntegerMatrix status_high, NumericMatrix time_low, IntegerMatrix status_low, NumericVector weights_high, NumericVector weights_low);
RcppExport SEXP _mrwin_mrwin_fast_pair_cpp(SEXP time_highSEXP, SEXP status_highSEXP, SEXP time_lowSEXP, SEXP status_lowSEXP, SEXP weights_highSEXP, SEXP weights_lowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type time_high(time_highSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type status_high(status_highSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type time_low(time_lowSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type status_low(status_lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights_high(weights_highSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights_low(weights_lowSEXP);
    rcpp_result_gen = Rcpp::wrap(mrwin_fast_pair_cpp(time_high, status_high, time_low, status_low, weights_high, weights_low));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mrwin_mrwin_fast_pair_cpp", (DL_FUNC) &_mrwin_mrwin_fast_pair_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mrwin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
