# Native interface for the optional Rust backend.
#
# In the standard extendr workflow this file is generated by
# `rextendr::register_extendr()`; regenerate it if you change the Rust
# signatures. The DLL registration is declared in NAMESPACE via
#   useDynLib(mrwin, .registration = TRUE)
#
# The run-time backend (R/backend_rust.R) calls the routine directly via
# .Call() guarded by .mrwin_rust_available(); this thin wrapper mirrors the
# extendr layout and uses the string form so that R CMD check does not flag an
# undefined symbol when the package is built without the Rust toolchain.

rust_pair_win_loss <- function(th, dh, wh, tl, dl, wl, k) {
  .Call("wrap__rust_pair_win_loss", th, dh, wh, tl, dl, wl, k, PACKAGE = "mrwin")
}
