# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrwin_subject_win_loss_cpp <- function(time_s, status_s, time_o, status_o, weights_o) {
    .Call(`_mrwin_mrwin_subject_win_loss_cpp`, time_s, status_s, time_o, status_o, weights_o)
}

mrwin_fast_pair_cpp <- function(time_high, status_high, time_low, status_low, weights_high, weights_low) {
    .Call(`_mrwin_mrwin_fast_pair_cpp`, time_high, status_high, time_low, status_low, weights_high, weights_low)
}

